# Specify the version for docker-compose.yml
version: "3.8"

# add the serivces needed (postgres,go)
services:
  postgres:
    container_name: transactionsdb
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    volumes: 
      - dbdata:/var/lib/postgresql/data

#  go:
#    container_name: go
#    # build the Dockerfile, alternatively use an image.
#    build:
#      context: .
#    depends_on:
#      - "postgres"
#      - "neo4j"
#      - "couchdb"

volumes:
  dbdata:
    driver: local