# Specify the version for docker-compose.yml
version: "3.8"

# add the serivces needed (postgres,go)
services:
  app:
    container_name: api-server
    environment:
      - POSTGRES_USER=$(DB_USER)
      - POSTGRES_PASSWORD=$(DB_PASSWORD)
      - POSTGRES_DB=$(DB_NAME)
      - DATABASE_HOST=$(DB_HOST)
      - DATABASE_PORT=$(DB_PORT)
    build: .
    depends_on:
      - postgres
    ports:
      - '8000:8080'
    networks:
      - learning

  postgres:
    container_name: transactionsdb
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: "transactions"
    ports:
      - "5432:5432"
    volumes: 
      - dbdata:/var/lib/postgresql/data
    networks:
      - learning

  dbtest:
    container_name: testdb
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: $(DB_NAME)
    ports:
      - "5432:5432"
    volumes: 
      - dbdata:/var/lib/postgresql/data
    networks:
      - learning

networks:
  learning:
    driver: bridge

volumes:
  dbdata:
    driver: local